export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const LOGOUT = 'LOGOUT';

export const CLEAR_PROFILE = "CLEAR_PROFILE"

export const CREATE_TRANSACTION_FAILED = "CREATE_TRANSACTION_FAILED"

export const FETCH_SHARE_NAME = "FETCH_SHARE_NAME"

export const FETCH_TRANSACTION = "FETCH_TRANSACTION"

export const FETCH_COMPANIES = "FETCH_COMPANIES"

export const FETCH_COMPANY = "FETCH_COMPANY"

export const FETCH_DASHBOARD = "FETCH_DASHBOARD"